# Generated by Django 4.2 on 2023-05-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nome',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_user', to='barber_shop.company', verbose_name='Gerente de'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_google',
            field=models.TextField(default='', max_length=500, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
