# Generated by Django 4.2.3 on 2023-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_nome_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('barbeiro', 'Barbeiro')], default='', max_length=50, verbose_name='Tipo do usuário'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome'),
        ),
    ]
