# Generated by Django 4.2.3 on 2023-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_type_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='Dono de alguma barbearia?'),
        ),
    ]
