# Generated by Django 4.2.3 on 2023-07-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Descrição de usuário'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de perfil'),
        ),
    ]
