# Generated by Django 4.2.3 on 2023-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbousUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developed_by', models.CharField(verbose_name='Desenvolvido por:')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email para contato:')),
                ('phone', models.CharField(verbose_name='Telefone para contato:')),
            ],
            options={
                'verbose_name': 'Sobre nós',
                'verbose_name_plural': 'Sobre nós',
            },
        ),
    ]
