# Generated by Django 4.2.3 on 2023-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abousus',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
