# Generated by Django 4.2.3 on 2023-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_abousus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abousus',
            name='developed_by',
            field=models.CharField(max_length=150, verbose_name='Desenvolvido por:'),
        ),
        migrations.AlterField(
            model_name='abousus',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefone para contato:'),
        ),
    ]
