# Generated by Django 4.2 on 2023-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome da Barbearia')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=12, verbose_name='Cep')),
                ('city', models.CharField(max_length=60, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=60, verbose_name='Bairro')),
                ('state', models.CharField(default='', max_length=60, verbose_name='Estado')),
                ('street', models.CharField(max_length=150, verbose_name='Rua e número')),
                ('instagram_link', models.URLField(max_length=250, verbose_name='Link do instagram')),
                ('facebook_link', models.URLField(max_length=250, verbose_name='Link do facebook')),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
            },
        ),
    ]
