# Generated by Django 4.2 on 2023-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='Horário de Funcionamento'),
        ),
    ]
