# Generated by Django 4.2.3 on 2023-07-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barber_shop', '0002_company_business_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Horário agendado')),
                ('confirmed_by_barber', models.BooleanField(default=True, verbose_name='Agendamento confirmado pelo barbeiro?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
    ]
