# Generated by Django 4.2.3 on 2023-07-18 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barber_shop', '0004_alter_schedules_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_barber', to=settings.AUTH_USER_MODEL, verbose_name='Dono(a)'),
        ),
    ]
