# Generated by Django 4.2.3 on 2023-07-19 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0005_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opening_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='Horário de Funcionamento'),
        ),
    ]
