# Generated by Django 4.2.3 on 2023-07-20 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barber_shop', '0009_alter_company_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employees_barber', to=settings.AUTH_USER_MODEL, verbose_name='Funcionários'),
        ),
    ]
