# Generated by Django 4.2.3 on 2023-07-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0011_alter_schedules_confirmed_by_barber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_business', models.DateTimeField(auto_created=True, null=True, verbose_name='Horário de Funcionamento')),
                ('day', models.CharField(max_length=50, verbose_name='Dia')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_dat', to='barber_shop.company', verbose_name='Barbearia')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
    ]
