# Generated by Django 4.2.3 on 2023-07-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0012_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='hours_business',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Horário de Funcionamento'),
        ),
    ]
