# Generated by Django 4.2.3 on 2023-07-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0014_company_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Link do facebook'),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Link do instagram'),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Link do Whatsapp'),
        ),
    ]
