# Generated by Django 4.2.3 on 2023-07-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0015_alter_company_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='hours_business',
        ),
        migrations.AddField(
            model_name='days',
            name='end',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Horário de encerramento'),
        ),
        migrations.AddField(
            model_name='days',
            name='start',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Horário de inicio'),
        ),
    ]
