# Generated by Django 4.2.3 on 2023-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0016_remove_days_hours_business_days_end_days_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='pause_time',
            field=models.TimeField(blank=True, help_text='opcional', null=True, verbose_name='Horário de pausa'),
        ),
    ]
