# Generated by Django 4.2.3 on 2023-08-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0019_days_end_pause_time_schedules_barbershop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='working_day',
            field=models.BooleanField(default=True, verbose_name='Dia de funcionamento'),
        ),
    ]
